server {
    listen 4200;

    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass http://backend:9292;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
